version: 2
jobs:
  "RxOptional Tests":
    working_directory: ~/RxSwiftCommunity/RxOptional
    parallelism: 1
    shell: /bin/bash --login
    environment:
      XCODE_TEST_REPORTS: /tmp/xcode-test-results
      LANG: en_US.UTF-8
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS $XCODE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run:
          name: Bootstrap Carthage
          command: scripts/bootstrap-if-needed.sh
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - Carthage
      - run:
          name: Test macOS, Swift 5
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=5.0 -scheme "RxOptional macOS" -project RxOptional.xcodeproj -sdk macosx -destination "arch=x86_64" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/macOS_swift5.html
      - run:
          name: Test macOS, Swift 4.2
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=4.2 -scheme "RxOptional macOS" -project RxOptional.xcodeproj -sdk macosx -destination "arch=x86_64" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/macOS_swift4_2.html
      - run:
          name: Test iOS, Swift 5
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=5.0 -scheme "RxOptional iOS" -project RxOptional.xcodeproj -sdk iphonesimulator -destination "name=iPhone X" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/iOS_swift5.html
      - run:
          name: Test iOS, Swift 4.2
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=4.2 -scheme "RxOptional iOS" -project RxOptional.xcodeproj -sdk iphonesimulator -destination "name=iPhone X" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/iOS_swift4.2.html
      - run:
          name: Test tvOS, Swift 5
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=5.0 -scheme "RxOptional tvOS" -project RxOptional.xcodeproj -sdk appletvsimulator -destination "name=Apple TV 4K (at 1080p)" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/tvOS_swift5.html
      - run:
          name: Test tvOS, Swift 4.2
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=4.2 -scheme "RxOptional tvOS" -project RxOptional.xcodeproj -sdk appletvsimulator -destination "name=Apple TV 4K (at 1080p)" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/tvOS_swift4_2.html
      - run:
          name: Test Swift Package
          command: swift test | xcpretty -c -r html --output $XCODE_TEST_REPORTS/SPM_swift5.html
      - store_artifacts:
          path: /tmp/xcode-test-results
  "RxOptional Release":
    working_directory: ~/RxSwiftCommunity/RxOptional
    parallelism: 1
    shell: /bin/bash --login
    environment:
      LANG: en_US.UTF-8
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run:
          name: Setup CocoaPods
          command: pod setup
      - run:
          name: Override Circle CI Config
          command: rm ~/.cocoapods/config.yaml # This hack is needed since CircleCI forces --verbose
      - run:
          name: Push Podspec to Trunk
          command: pod trunk push --skip-tests --allow-warnings
workflows:
  version: 2
  build:
    jobs:
      - "RxOptional Tests":
          filters:
            tags:
              ignore: /[0-9]+(\.[0-9]+)*/
  release:
    jobs:
      - "RxOptional Release":
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
